'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type LanguageCode = 'es' | 'en'

interface LanguageContextType {
  language: LanguageCode
  setLanguage: (lang: LanguageCode) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>('en')

  useEffect(() => {
    const savedLang = localStorage.getItem('virtus_language') as LanguageCode
    if (savedLang === 'es' || savedLang === 'en') {
      setLanguageState(savedLang)
    }
    // Default is 'en' if nothing saved
  }, [])

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang)
    localStorage.setItem('virtus_language', lang)
  }

  const t = (key: string): string => {
    const keys = key.split('.')
    let value: any = translations[language]
    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k]
      } else {
        // Fallback to English
        let fallback: any = translations['en']
        for (const fk of keys) {
          if (fallback && typeof fallback === 'object') fallback = fallback[fk]
          else return key
        }
        return typeof fallback === 'string' ? fallback : key
      }
    }
    return typeof value === 'string' ? value : key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within LanguageProvider')
  return context
}

const translations: Record<LanguageCode, any> = {
  en: {
    nav: {
      home: 'Home',
      market: 'Market',
      trading: 'Trading',
      futures: 'Futures',
      wallet: 'Wallet',
      team: 'Team',
      vip: 'Plans',
      myPurchases: 'My Plans',
      network: 'Network',
      kyc: 'KYC',
      admin: 'Admin',
      logout: 'Logout',
    },
    common: {
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      cancel: 'Cancel',
      confirm: 'Confirm',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      view: 'View',
      close: 'Close',
      search: 'Search',
      filter: 'Filter',
      all: 'All',
      yes: 'Yes',
      no: 'No',
      retry: 'Try again',
      allRightsReserved: '© Virtus. All rights reserved.',
      copyright: '© Virtus. All rights reserved. Content and brand are protected by applicable law.',
      pending: 'Pending',
      active: 'Active',
      rejected: 'Rejected',
      cancelled: 'Cancelled',
      approved: 'Approved',
      level: 'Level',
      investment: 'Investment',
      dailyProfit: 'Daily Profit',
      noData: 'No data available',
    },
    welcome: {
      tagline: 'Your financial future',
      login: 'Sign In',
      register: 'Create Account',
    },
    home: {
      welcome: 'Welcome',
      balance: 'Total Balance',
      dailyProfit: 'Daily Profit',
      totalEarnings: 'Total Earnings',
      referrals: 'Referrals',
      rank: 'No Rank',
      currentRank: 'Current Rank',
      capital: 'Futures Capital',
      todayEarnings: "Today's Earnings",
      weekEarnings: 'This Week',
      monthEarnings: 'This Month',
      allTimeEarnings: 'All Time',
      copyLink: 'Copy link',
      code: 'Code',
      earnings: 'Earnings',
      referralBonus: 'Referral Bonus',
      sharedBonus: 'Shared Bonus',
      extras: 'Extras',
      noActivePlan: 'No active plan',
      activatePlan: 'Activate a plan',
      sponsor: 'Sponsored by',
      directReferrals: 'Direct referrals',
      totalNetwork: 'Total network',
      inviteLink: 'Invite Link',
      copyCode: 'Copy code',
      copied: 'Copied!',
      myPurchases: 'My Purchases',
      injectCapital: 'Invest Capital',
      sponsorship: 'Sponsorship',
      levels: '3 levels',
      level: 'Lv',
      shared: 'Shared',
      sharedFrom: 'from {{name}}',
      sharedDistributed: '1.5% distributed',
      noBonuses: 'No bonuses yet',
      extrasLabel: 'Extras',
      movements: '{{n}} movements',
      noExtras: 'No extras',
      noExtrasBonuses: 'No extra bonuses',
      myNetwork: 'My Network',
      directs: 'Directs',
      copyReferralLink: 'COPY REFERRAL LINK',
      loading: 'Loading data...',
      retry: 'Retry',
      goLogin: 'Go to Login',
      updatePhoto: 'Update profile photo',
      photoDesc: 'Select a photo from your device (max. 5MB)',
      noPhoto: 'No photo',
      selectImage: 'Select image',
      uploading: 'Uploading...',
      savePhoto: 'Save photo',
      continueBtn: 'Continue',
      visitSite: 'Visit Official Website',
      taskRate: 'Please rate and comment on the image',
      taskDone: 'Task completed',
      taskError: 'Error completing task',
      sessionExpired: 'Your session expired. Please sign in again.',
      linkCopied: 'Link copied',
      linkCopyFailed: 'Could not copy link',
      imageTooBig: 'Image must be smaller than 5MB',
      selectImageRequired: 'Please select an image',
      uploadError: 'Error uploading image',
      updatePhotoError: 'Error updating photo',
      earningsSummary: 'EARNINGS SUMMARY',
      last7days: 'Last 7 days',
      today: 'Today',
      yesterday: 'Yesterday',
      week: 'Week',
      accumulated: 'Accumulated',
    },
    mercado: {
      crypto: 'Crypto',
      futures: 'Futures',
      forex: 'Forex',
      indices: 'Indices',
      stocks: 'Stocks',
      commodities: 'Commodities',
      markets: 'Markets',
      asset: 'Asset',
      price: 'Price',
      loading: 'Loading market...',
      noConnection: 'No market connection.\nRetrying every 10s...',
      noData: 'No data available',
    },
    trading: {
      active: 'Active',
      history: 'History',
      signals: 'Signals',
      rise: 'RISE',
      fall: 'FALL',
      investment: 'Investment',
      close: 'Close',
      noActiveOrders: 'No active orders',
      openPosition: 'Open a position to see it here',
      noHistory: 'No trade history',
      profit: 'PROFIT',
      loss: 'LOSS',
      activeCode: 'ACTIVE CODE',
      buyRise: 'BUY (RISE)',
      sellFall: 'SELL (FALL)',
      waitingSignal: 'Waiting for signal...',
      signalExecuted: 'Signal Executed!',
      operationRunning: 'Operation running or completed.',
      enterCode: 'Enter Code',
      activateSignal: 'ACTIVATE SIGNAL',
      up: 'UP',
      down: 'DOWN',
      leverage: 'Leverage',
      tpOptional: 'TP (Optional)',
      slOptional: 'SL (Optional)',
      confirm: 'CONFIRM',
      operationOpen: 'OPERATION OPENED',
      previousCapital: 'Previous capital',
      operation: 'Operation (1%)',
      viewOperation: 'View Operation',
      markets: 'Markets',
      insufficientBalance: 'Insufficient balance',
      copy: 'COPY',
      marketPrice: 'Market Price',
      live: 'Live',
      errorOpening: 'Error opening position',
      errorConnection: 'Connection error',
      signalError: 'Error executing signal',
      notAuthenticated: 'Not authenticated',
    },
    vip: {
      title: 'VIRTUS Plans',
      subtitle: 'Choose your investment plan',
      active: 'ACTIVE',
      pending: 'PENDING',
      rejected: 'REJECTED',
      investment: 'Investment',
      dailyProfit: 'Daily Profit',
      selectPlan: 'Activate',
      currentPlan: 'Current Plan',
      paymentMethod: 'Payment Method',
      uploadProof: 'Upload Proof',
      submit: 'Submit Request',
      processing: 'Processing...',
      signals: 'Signals',
      sponsorBonus: 'Sponsorship Bonus',
      sharedBonus: 'Shared Benefit 8.5%',
      upgrade: 'Upgrade',
      blocked: 'Locked',
      notAvailable: 'Not Available',
      pays: 'You pay',
    },
    myPurchases: {
      title: 'My Plans',
      subtitle: 'Acquired VIRTUS plans',
      noPurchases: 'You have no registered purchases',
      upgradedTitle: 'Congratulations! You upgraded',
      upgradedMsg: 'You now have the',
      purchased: 'Purchased',
      activated: 'Activated',
    },
    withdrawals: {
      title: 'Wallet',
      balance: 'Available Balance',
      withdraw: 'Request Withdrawal',
      history: 'Withdrawal History',
      noHistory: 'No withdrawal history',
      amount: 'Amount (USDT)',
      amountPlaceholder: 'E.g. 25.50',
      binanceId: 'Binance ID / Wallet',
      binancePlaceholder: 'Your Binance ID',
      qrCode: 'QR Code (Binance Pay)',
      qrHelp: 'Open Binance → Receive → QR. Take a screenshot and upload it.',
      qrTap: 'Tap to upload QR',
      qrChange: 'Tap to change',
      method: 'Method',
      methodPlaceholder: 'E.g. USDT BEP-20',
      phone: 'Phone (optional)',
      phonePlaceholder: 'WhatsApp number',
      submit: 'Request Withdrawal',
      submitting: 'Submitting...',
      minAmount: 'Minimum withdrawal: $30',
      conditions: 'Withdrawal Conditions',
      cond1Title: 'Active plan',
      cond1Desc: 'You must have at least one active VIRTUS plan',
      cond2Title: 'Double investment',
      cond2Desc: 'Your balance must be ≥ 2× your initial investment',
      cond3Title: 'KYC verified',
      cond3Desc: 'Your identity must be verified before withdrawing',
      cond4Title: 'Minimum $1',
      cond4Desc: 'Minimum withdrawal amount: $1 USDT',
      progressTitle: 'Progress to unlock withdrawal',
      progressNeeds: 'You need',
      progressMore: 'more to withdraw',
      kycNotVerified: 'Verify your identity before requesting withdrawals.',
      kycPending: 'Your identity verification is under review. Wait for approval.',
      kycRejected: 'Your verification was rejected. Please resubmit your documents.',
      kycGoVerify: 'Verify identity now',
      kycCheckStatus: 'Check verification status',
      statusPending: 'Pending',
      statusPaid: 'Paid',
      statusRejected: 'Rejected',
      subtitle: 'Request your withdrawal',
      withdrawalDays: 'Withdrawal Days',
      withdrawalDaysDesc: 'Monday to Friday (business days)',
      withdrawalDaysNote: 'Saturdays, Sundays and holidays are not processed',
      discount: '{{pct}}% Discount',
      discountDesc: 'A {{pct}}% commission is applied to the requested amount',
      discountExample: 'Example: Withdraw $100 → Receive ${{net}}',
      processingTime: 'Processing Time',
      processingTimeDesc: 'Your payment will be credited in 24 to 72 business hours',
      processingTimeNote: 'You will receive proof when completed',
      requirement: 'Requirement',
      requirementDesc: 'You must have at least one active VIRTUS plan',
      withdrawalUnlocked: 'Withdrawal unlocked',
      progressBar: 'Progress to withdraw',
      yourBalance: 'Your balance',
      goal: 'Goal',
      xInvestment: '2x investment',
      needMore: 'You need ${{amount}} more to withdraw',
      enterAmount: 'Enter Amount',
      amountLabel: 'Amount to withdraw (minimum $1)',
      requested: 'Requested amount',
      discountLabel: 'Discount ({{pct}}%)',
      youReceive: 'You receive',
      qrLoaded: 'QR loaded',
      uploadQr: 'Upload your wallet QR',
      qrLabel: 'QR of your Wallet to receive',
      kycPendingTitle: 'Verification under review',
      kycRejectedTitle: 'Verification rejected',
      kycRequiredTitle: 'Verification required',
      receiptAttached: 'Proof attached',
    },
    kyc: {
      title: 'Identity Verification',
      subtitle: 'KYC — Know your customer',
      approvedTitle: 'Identity Verified',
      approvedDesc: 'Your account is verified and you can request withdrawals',
      pendingTitle: 'Under Review',
      pendingDesc: 'The team will review your documents soon',
      rejectedTitle: 'Verification Rejected',
      rejectedReason: 'Reason',
      canResubmit: 'You can resubmit your documents',
      whatToUpload: 'What do you need to upload?',
      selfieTitle: 'Selfie holding your ID',
      selfieDesc: 'Photo of you with your ID/passport visible in your hand',
      frontTitle: 'Front of ID',
      frontDesc: 'Clear photo of the front of your ID/passport',
      backTitle: 'Back of ID',
      backDesc: 'Clear photo of the back of your ID/passport',
      submit: 'Submit for Verification',
      submitting: 'Sending documents...',
      photoLoaded: 'Photo loaded',
      tapChange: 'Tap to change',
      tapTake: 'Tap to take photo',
      sendAll3: 'You must upload all 3 photos',
    },
    network: {
      title: 'My Network',
      total: 'Total',
      noReferrals: 'Single-person network',
      noReferralsDesc: 'You have no referrals registered below you.',
      inviteDesc: 'Invite users to see your tree grow.',
      loadingNetwork: 'Loading network...',
      loadingTree: 'Loading network tree...',
      referrals: 'Referrals',
      activePlans: 'Active Plans',
      packages: 'VIRTUS Plans',
      viewProfile: 'View Full Profile',
      retry: 'Retry',
    },
    login: {
      title: 'Sign in to your account',
      username: 'Username or Email',
      password: 'Password',
      submit: 'Sign In',
      noAccount: "Don't have an account?",
      register: 'Register',
      forgotPassword: 'Forgot password?',
    },
    signup: {
      title: 'Create Account',
      sponsor: 'Sponsor Code',
      fullName: 'Full Name',
      country: 'Country',
      selectCountry: '— Select —',
      username: 'Username or Gmail',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      carnet: 'ID/Passport Number',
      submit: 'Register',
      submitting: 'Registering...',
      hasAccount: 'Already have an account?',
      login: 'Sign in',
      success: 'Registration Successful',
      credentials: 'Save your credentials',
    },
    admin: {
      title: 'Admin Panel',
      users: 'Users',
      purchases: 'Wallet',
      withdrawals: 'Withdrawals',
      futuros: 'Futures',
      signals: 'Signals',
      approve: 'Approve',
      reject: 'Reject',
      total: 'Total',
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
    },
    futuros: {
      title: 'Futures Trading',
      signals: 'Signals',
      wallet: 'Wallet',
      code: 'Code',
      activeSignal: 'Active Signal',
      enterCode: 'Enter Code',
      execute: 'Execute',
      executed: 'EXECUTED',
      profit: 'Profit',
      globalBonus: 'Global Bonus',
      capitalBefore: 'Previous Capital',
      capitalAfter: 'New Capital',
      currentCapital: 'Current Capital',
      history: 'History',
      options: 'Options',
      price: 'Price',
      amount: 'Amount',
      available: 'Available',
      marketPrice: 'Market Price',
      positions: 'Positions',
      openOrders: 'Open Orders',
      bots: 'Bots',
      noPosition: 'No open positions',
      noHistory: 'No trade history',
      chartLabel: 'Chart of {{pair}} Perpetual',
      confirmOrder: 'Confirm Order',
      confirmText: 'You are about to open a {{type}} position of {{amount}} USDT in {{pair}}.',
      buy: 'Buy',
      sell: 'Sell',
      crossed: 'Crossed',
      markets: 'Markets',
      priceUsdt: 'Price (USDT)',
      amountUsdt: 'Amount (USDT)',
      funding: 'Funding / Countdown',
      insufficientBalance: 'Insufficient balance',
      errorOpening: 'Error opening order',
      errorConnection: 'Connection error',
    },
    buy: {
      loading: 'Loading...',
      notFound: 'Package not found',
      loadError: 'Error loading package',
      upgradeActivated: 'Upgrade Activated',
      packageActivated: 'Package Activated',
      active: 'ACTIVE',
      upgradeSuccess: 'Your plan has been upgraded to {{name}} successfully.',
      packageSuccess: 'Your {{name}} has been activated successfully.',
      dailyProfitActive: 'Your daily earnings of ${{amount}} USDT are now active.',
      viewOnBscscan: 'View transaction on BscScan',
      viewPurchases: 'View My Purchases',
      backToPackages: 'Back to Packages',
      paymentNotVerified: 'Payment Not Verified',
      rejected: 'REJECTED',
      rejectedDesc: 'The transaction could not be verified. Make sure you sent the correct amount in USDT (BEP-20) to the correct address.',
      tryAgain: 'Try Again',
      verifying: 'Verifying on Blockchain',
      confirmations: '{{count}}/{{total}} confirmations',
      verifyingDesc: 'Your package will be activated automatically once confirmations are complete. You can close this page.',
      upgradePlan: 'Plan Upgrade',
      completeYourPurchase: 'Complete your purchase',
      currentPlan: 'Current plan',
      newPlan: 'New plan',
      investment: 'Investment',
      payNow: 'You pay now',
      dailyProfit: 'Daily profit',
      upgradeNoBonus: 'Upgrades do not generate referral bonuses or shared benefits',
    },
  },

  es: {
    nav: {
      home: 'Inicio',
      market: 'Mercado',
      trading: 'Trading',
      futures: 'Futuros',
      wallet: 'Billetera',
      team: 'Equipo',
      vip: 'Planes',
      myPurchases: 'Mis Planes',
      network: 'Red',
      kyc: 'KYC',
      admin: 'Admin',
      logout: 'Salir',
    },
    common: {
      loading: 'Cargando...',
      error: 'Error',
      success: 'Éxito',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      save: 'Guardar',
      delete: 'Eliminar',
      edit: 'Editar',
      view: 'Ver',
      close: 'Cerrar',
      search: 'Buscar',
      filter: 'Filtrar',
      all: 'Todos',
      yes: 'Sí',
      no: 'No',
      retry: 'Reintentar',
      allRightsReserved: '© Virtus. Todos los derechos reservados.',
      copyright: '© Virtus. Todos los derechos reservados. El contenido y la marca están protegidos por la legislación vigente.',
      pending: 'Pendiente',
      active: 'Activo',
      rejected: 'Rechazado',
      cancelled: 'Cancelado',
      approved: 'Aprobado',
      level: 'Nivel',
      investment: 'Inversión',
      dailyProfit: 'Ganancia Diaria',
      noData: 'Sin datos disponibles',
    },
    home: {
      welcome: 'Bienvenido',
      balance: 'Balance Total',
      dailyProfit: 'Ganancia Diaria',
      totalEarnings: 'Ganancias Totales',
      referrals: 'Referidos',
      rank: 'Sin Rango',
      currentRank: 'Rango Actual',
      capital: 'Capital Futuros',
      todayEarnings: 'Ganancias de Hoy',
      weekEarnings: 'Esta Semana',
      monthEarnings: 'Este Mes',
      allTimeEarnings: 'Total Histórico',
      copyLink: 'Copiar link',
      code: 'Código',
      earnings: 'Ganancias',
      referralBonus: 'Bono de Referido',
      sharedBonus: 'Bono Compartido',
      extras: 'Extras',
      noActivePlan: 'Sin plan activo',
      activatePlan: 'Activa un plan',
      sponsor: 'Patrocinado por',
      directReferrals: 'Referidos directos',
      totalNetwork: 'Red total',
      inviteLink: 'Link de Invitación',
      copyCode: 'Copiar código',
      copied: '¡Copiado!',
      myPurchases: 'Mis Compras',
      injectCapital: 'Inyectar Capital',
      sponsorship: 'Patrocinio',
      levels: '3 niveles',
      level: 'Nv',
      shared: 'Compartido',
      sharedFrom: 'de {{name}}',
      sharedDistributed: '1.5% repartido',
      noBonuses: 'Sin bonos aún',
      extrasLabel: 'B. Extra',
      movements: '{{n}} movimientos',
      noExtras: 'Sin extras',
      noExtrasBonuses: 'Sin bonos extra',
      myNetwork: 'Mi Red',
      directs: 'Directos',
      copyReferralLink: 'COPIAR LINK DE REFERIDO',
      loading: 'Cargando datos...',
      retry: 'Reintentar',
      goLogin: 'Ir a Login',
      updatePhoto: 'Actualizar foto de perfil',
      photoDesc: 'Selecciona una foto desde tu dispositivo (máx. 5MB)',
      noPhoto: 'Sin foto',
      selectImage: 'Seleccionar imagen',
      uploading: 'Subiendo...',
      savePhoto: 'Guardar foto',
      continueBtn: 'Continuar',
      visitSite: 'Visitar Sitio Web Oficial',
      taskRate: 'Por favor califica y comenta la imagen',
      taskDone: 'Tarea completada',
      taskError: 'Error al completar tarea',
      sessionExpired: 'Tu sesión expiró. Inicia sesión nuevamente.',
      linkCopied: 'Link copiado',
      linkCopyFailed: 'No se pudo copiar el link',
      imageTooBig: 'La imagen debe ser menor a 5MB',
      selectImageRequired: 'Por favor selecciona una imagen',
      uploadError: 'Error al subir la imagen',
      updatePhotoError: 'Error al actualizar la foto',
      earningsSummary: 'RESUMEN DE GANANCIAS',
      last7days: 'Últimos 7 días',
      today: 'Hoy',
      yesterday: 'Ayer',
      week: 'Semana',
      accumulated: 'Acumulado',
    },
    welcome: {
      tagline: 'Tu futuro financiero',
      login: 'Iniciar Sesión',
      register: 'Crear Cuenta',
    },
    mercado: {
      crypto: 'Criptos',
      futures: 'Futuros',
      forex: 'Divisas',
      indices: 'Índices',
      stocks: 'Acciones',
      commodities: 'Materias Primas',
      markets: 'Mercados',
      asset: 'Activo',
      price: 'Precio',
      loading: 'Cargando mercado...',
      noConnection: 'Sin conexión con el mercado.\nReintentando cada 10s...',
      noData: 'No hay datos disponibles',
    },
    trading: {
      active: 'Activas',
      history: 'Historial',
      signals: 'Señales',
      rise: 'ALZA',
      fall: 'BAJA',
      investment: 'Inversión',
      close: 'Cerrar',
      noActiveOrders: 'Sin órdenes activas',
      openPosition: 'Abre una posición para verla aquí',
      noHistory: 'Sin historial de operaciones',
      profit: 'BENEFICIO',
      loss: 'PÉRDIDA',
      activeCode: 'CÓDIGO ACTIVO',
      buyRise: 'COMPRA (ALZA)',
      sellFall: 'VENTA (BAJA)',
      waitingSignal: 'Esperando señal...',
      signalExecuted: '¡Señal Ejecutada!',
      operationRunning: 'Operación en curso o finalizada.',
      enterCode: 'Ingresar Código',
      activateSignal: 'ACTIVAR SEÑAL',
      up: 'SUBIDA',
      down: 'BAJADA',
      leverage: 'Apalancamiento',
      tpOptional: 'TP (Opcional)',
      slOptional: 'SL (Opcional)',
      confirm: 'CONFIRMAR',
      operationOpen: 'OPERACIÓN ABIERTA',
      previousCapital: 'Capital anterior',
      operation: 'Operación (1%)',
      viewOperation: 'Ver Operación',
      markets: 'Mercados',
      insufficientBalance: 'Saldo insuficiente',
      copy: 'COPIAR',
      marketPrice: 'Precio de Mercado',
      live: 'En vivo',
      errorOpening: 'Error al abrir posición',
      errorConnection: 'Error de conexión',
      signalError: 'Error al ejecutar señal',
      notAuthenticated: 'No autenticado',
    },
    vip: {
      title: 'Planes VIRTUS',
      subtitle: 'Elige tu plan de inversión',
      active: 'ACTIVO',
      pending: 'PENDIENTE',
      rejected: 'RECHAZADO',
      investment: 'Inversión',
      dailyProfit: 'Ganancia Diaria',
      selectPlan: 'Activar',
      currentPlan: 'Plan Actual',
      paymentMethod: 'Método de Pago',
      uploadProof: 'Subir Comprobante',
      submit: 'Enviar Solicitud',
      processing: 'Procesando...',
      signals: 'Señales',
      sponsorBonus: 'Bono Patrocinio',
      sharedBonus: 'Beneficio Compartido 8.5%',
      upgrade: 'Upgrade',
      blocked: 'Bloqueado',
      notAvailable: 'No Disponible',
      pays: 'Pagas',
    },
    myPurchases: {
      title: 'Mis Planes',
      subtitle: 'Paquetes JADE adquiridos',
      noPurchases: 'No tienes compras registradas',
      upgradedTitle: '¡Felicidades! Ya hiciste upgrade',
      upgradedMsg: 'Ahora tienes el paquete',
      purchased: 'Comprado',
      activated: 'Activado',
    },
    withdrawals: {
      title: 'Billetera',
      balance: 'Balance Disponible',
      withdraw: 'Solicitar Retiro',
      history: 'Historial de Retiros',
      noHistory: 'Sin historial de retiros',
      amount: 'Monto (USDT)',
      amountPlaceholder: 'Ej. 25.50',
      binanceId: 'ID de Binance / Billetera',
      binancePlaceholder: 'Tu ID de Binance',
      qrCode: 'Código QR (Binance Pay)',
      qrHelp: 'Abre Binance → Recibir → QR. Toma captura y súbela.',
      qrTap: 'Toca para subir QR',
      qrChange: 'Toca para cambiar',
      method: 'Método',
      methodPlaceholder: 'Ej. USDT BEP-20',
      phone: 'Teléfono (opcional)',
      phonePlaceholder: 'Número de WhatsApp',
      submit: 'Solicitar Retiro',
      submitting: 'Enviando...',
      minAmount: 'Mínimo de retiro: $30',
      conditions: 'Condiciones de retiro',
      cond1Title: 'Plan activo',
      cond1Desc: 'Debes tener al menos un plan VIRTUS activo',
      cond2Title: 'Duplicar inversión',
      cond2Desc: 'Tu balance debe ser ≥ 2× tu inversión inicial',
      cond3Title: 'KYC verificado',
      cond3Desc: 'Tu identidad debe estar verificada antes de retirar',
      cond4Title: 'Mínimo $1',
      cond4Desc: 'Monto mínimo de retiro: $1 USDT',
      progressTitle: 'Progreso para desbloquear retiro',
      progressNeeds: 'Necesitas',
      progressMore: 'más para retirar',
      kycNotVerified: 'Debes verificar tu identidad antes de solicitar retiros.',
      kycPending: 'Tu verificación de identidad está en revisión. Espera la aprobación.',
      kycRejected: 'Tu verificación fue rechazada. Por favor vuelve a enviar tus documentos.',
      kycGoVerify: 'Verificar identidad ahora',
      kycCheckStatus: 'Ver estado de verificación',
      statusPending: 'Pendiente',
      statusPaid: 'Pagado',
      statusRejected: 'Rechazado',
      subtitle: 'Solicita tu retiro',
      withdrawalDays: 'Días de retiro',
      withdrawalDaysDesc: 'Lunes a Viernes (días hábiles)',
      withdrawalDaysNote: 'Sábados, domingos y feriados no se procesan',
      discount: 'Descuento del {{pct}}%',
      discountDesc: 'Se aplica un {{pct}}% de comisión sobre el monto solicitado',
      discountExample: 'Ejemplo: Retiras $100 → Recibes ${{net}}',
      processingTime: 'Tiempo de procesamiento',
      processingTimeDesc: 'Tu pago se abonará en 24 a 72 horas hábiles',
      processingTimeNote: 'Recibirás comprobante cuando se complete',
      requirement: 'Requisito',
      requirementDesc: 'Debes tener al menos un plan VIRTUS activo',
      withdrawalUnlocked: 'Retiro desbloqueado',
      progressBar: 'Progreso para retirar',
      yourBalance: 'Tu saldo',
      goal: 'Meta',
      xInvestment: '2x inversión',
      needMore: 'Faltan ${{amount}} para poder retirar',
      enterAmount: 'Ingresa el Monto',
      amountLabel: 'Monto a retirar (mínimo $1)',
      requested: 'Monto solicitado',
      discountLabel: 'Descuento ({{pct}}%)',
      youReceive: 'Recibes',
      qrLoaded: 'QR cargado',
      uploadQr: 'Sube tu QR de tu Billetera',
      qrLabel: 'QR de tu Billetera para recibir',
      kycPendingTitle: 'Verificación en revisión',
      kycRejectedTitle: 'Verificación rechazada',
      kycRequiredTitle: 'Verificación requerida',
      receiptAttached: 'Comprobante adjunto',
    },
    kyc: {
      title: 'Verificación de Identidad',
      subtitle: 'KYC — Conoce a tu cliente',
      approvedTitle: 'Identidad Verificada',
      approvedDesc: 'Tu cuenta está verificada y puedes solicitar retiros',
      pendingTitle: 'En Revisión',
      pendingDesc: 'El equipo revisará tus documentos pronto',
      rejectedTitle: 'Verificación Rechazada',
      rejectedReason: 'Motivo',
      canResubmit: 'Puedes volver a enviar tus documentos',
      whatToUpload: '¿Qué necesitas subir?',
      selfieTitle: 'Selfie sosteniendo tu carnet',
      selfieDesc: 'Foto tuya con el carnet/cédula visible en tu mano',
      frontTitle: 'Frente del carnet',
      frontDesc: 'Foto clara del frente de tu CI/Cédula',
      backTitle: 'Reverso del carnet',
      backDesc: 'Foto clara del reverso de tu CI/Cédula',
      submit: 'Enviar para Verificación',
      submitting: 'Enviando documentos...',
      photoLoaded: 'Foto cargada',
      tapChange: 'Toca para cambiar',
      tapTake: 'Toca para tomar foto',
      sendAll3: 'Debes subir las 3 fotos',
    },
    network: {
      title: 'Mi Red',
      total: 'Total',
      noReferrals: 'Red Unipersonal',
      noReferralsDesc: 'Aún no tienes referidos registrados debajo de ti.',
      inviteDesc: 'Invita a usuarios para ver crecer tu árbol.',
      loadingNetwork: 'Cargando red...',
      loadingTree: 'Cargando árbol de red...',
      referrals: 'Referidos',
      activePlans: 'Paks Activos',
      packages: 'Paquetes JADE',
      viewProfile: 'Ver Perfil Completo',
      retry: 'Reintentar',
    },
    login: {
      title: 'Inicia sesión en tu cuenta',
      username: 'Usuario o Email',
      password: 'Contraseña',
      submit: 'Iniciar Sesión',
      noAccount: '¿No tienes cuenta?',
      register: 'Regístrate',
      forgotPassword: '¿Olvidaste tu contraseña?',
    },
    signup: {
      title: 'Crear Cuenta',
      sponsor: 'Código de Patrocinador',
      fullName: 'Nombre Completo',
      country: 'País',
      selectCountry: '— Selecciona —',
      username: 'Usuario o Gmail',
      email: 'Email',
      password: 'Contraseña',
      confirmPassword: 'Confirmar Contraseña',
      carnet: 'Número de CI/Cédula',
      submit: 'Registrarse',
      submitting: 'Registrando...',
      hasAccount: '¿Ya tienes cuenta?',
      login: 'Inicia sesión',
      success: 'Registro Exitoso',
      credentials: 'Guarda tus credenciales',
    },
    admin: {
      title: 'Panel de Administración',
      users: 'Usuarios',
      purchases: 'Billetera',
      withdrawals: 'Retiros',
      futuros: 'Futuros',
      signals: 'Señales',
      approve: 'Aprobar',
      reject: 'Rechazar',
      total: 'Total',
      pending: 'Pendientes',
      approved: 'Aprobadas',
      rejected: 'Rechazadas',
    },
    futuros: {
      title: 'Trading Futuros',
      signals: 'Señales',
      wallet: 'Billetera',
      code: 'Código',
      activeSignal: 'Señal Activa',
      enterCode: 'Ingresar Código',
      execute: 'Ejecutar',
      executed: 'EJECUTADA',
      profit: 'Ganancia',
      globalBonus: 'Bono Global',
      capitalBefore: 'Capital Anterior',
      capitalAfter: 'Capital Nuevo',
      currentCapital: 'Capital Actual',
      history: 'Historial',
      options: 'Opciones',
      price: 'Precio',
      amount: 'Monto',
      available: 'Disponible',
      marketPrice: 'Precio de Mercado',
      positions: 'Posiciones',
      openOrders: 'Órdenes Abiertas',
      bots: 'Bots',
      noPosition: 'No tiene ninguna posición abierta',
      noHistory: 'Sin historial de órdenes',
      chartLabel: 'Gráfico de {{pair}} Perpetual',
      confirmOrder: 'Confirmar Orden',
      confirmText: 'Estás a punto de abrir una posición {{type}} de {{amount}} USDT en {{pair}}.',
      buy: 'Comprar',
      sell: 'Vender',
      crossed: 'Cruzado',
      markets: 'Mercados',
      priceUsdt: 'Precio (USDT)',
      amountUsdt: 'Monto (USDT)',
      funding: 'Financiación / Cuenta reg.',
      insufficientBalance: 'Saldo insuficiente',
      errorOpening: 'Error al abrir la orden',
      errorConnection: 'Error de conexión',
    },
    buy: {
      loading: 'Cargando...',
      notFound: 'Paquete no encontrado',
      loadError: 'Error al cargar el paquete',
      upgradeActivated: 'Upgrade Activado',
      packageActivated: 'Paquete Activado',
      active: 'ACTIVO',
      upgradeSuccess: 'Tu plan ha sido actualizado a {{name}} exitosamente.',
      packageSuccess: 'Tu {{name}} ha sido activado exitosamente.',
      dailyProfitActive: 'Tus ganancias diarias de ${{amount}} USDT ya están activas.',
      viewOnBscscan: 'Ver transacción en BscScan',
      viewPurchases: 'Ver Mis Compras',
      backToPackages: 'Volver a Paquetes',
      paymentNotVerified: 'Pago No Verificado',
      rejected: 'RECHAZADO',
      rejectedDesc: 'La transacción no pudo ser verificada. Verifica que hayas enviado el monto correcto en USDT (BEP-20) a la dirección correcta.',
      tryAgain: 'Intentar de Nuevo',
      verifying: 'Verificando en Blockchain',
      confirmations: '{{count}}/{{total}} confirmaciones',
      verifyingDesc: 'Tu paquete se activará automáticamente al completar las confirmaciones. Puedes cerrar esta página.',
      upgradePlan: 'Upgrade de Plan',
      completeYourPurchase: 'Completa tu compra',
      currentPlan: 'Plan actual',
      newPlan: 'Nuevo plan',
      investment: 'Inversión',
      payNow: 'Pagas ahora',
      dailyProfit: 'Ganancia diaria',
      upgradeNoBonus: 'El upgrade no genera bonos de patrocinio ni beneficio compartido',
    },
  },
}
